# Generated by Django 3.1.1 on 2020-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201006_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(related_name='bids', through='auctions.Bids', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.Listing'),
        ),
    ]
